apiVersion: v1
kind: Service

metadata:
  name: elasticsearch-headless-service

spec:
  clusterIP: None
  selector:
    app: elasticsearch-pod
  ports:
    - name: user
      port: 9200
    - name: internal
      port: 9300