apiVersion: v1
kind: Service
metadata:
  name: eureka-internal-discovery

spec:
  selector:
    app: eureka-pod

  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30001
