spring.application.name=YT-AI
server.port=0
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true
# --- Spring ai ---
spring.ai.mistralai.api-key=${SPRING_AI_MISTRAL_API_KEY}
spring.ai.mistralai.chat.options.model=open-mistral-nemo-2407
spring.ai.chat.client.enabled=true
# --- Kafka ---
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.topic.name=${SPRING_KAFKA_TOPIC_YT}
# --- Mail ---
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
# --- YouTube ---
youtube.api.key=${YOUTUBE_API_KEY}
SEARCH_URL=https://www.googleapis.com/youtube/v3

