spring.application.name=SearchEngine-MicroService
# --- Port ---
server.port=0
# --- Kafka ---
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.topic.name.open-search=${SPRING_KAFKA_TOPIC_OPENSEARCH}
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URL}
# Elasticsearch configuration
elasticsearch.host=${ELASTICSEARCH_HOST}
elasticsearch.port=${ELASTICSEARCH_PORT}
elasticsearch.index=${ELASTICSEARCH_INDEX}
# Graph QL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
# --- AWS ---
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}
spring.threads.virtual.enabled=true