spring.application.name=Orchestrator
server.port=7450
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
#--------------------------------------
spring.ai.google.genai.api-key=${AI_STUDIO_GEMINI}
spring.ai.google.genai.chat.options.google-search-retrieval=true
#---------------------------------------
spring.ai.openai.api-key=${OPEN_ROUTER_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=arcee-ai/trinity-large-preview:free
#---------------------------------------
# MySQL Schema
spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema-mysql.sql
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:UserChatSchema.sql
#---------------------------------------
# MySQL database connection URL
spring.datasource.url=${MYSQL_URL}
# MySQL database username
spring.datasource.username=${MYSQL_USER}
# MySQL database password
spring.datasource.password=${MYSQL_PASS}
#-----------------------------------------
# Reactive
spring.r2dbc.username=${MYSQL_USER}
spring.r2dbc.password=${MYSQL_PASS}
spring.r2dbc.url=${Reactive_MYSQL_URL}
#---------------------------------------
# Eureka Spring Cloud
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
#-----------------------------------------
# Enable the MCP server
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.name=my-http-mcp-server
spring.ai.mcp.server.type=SYNC
